// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://pvvbyztbninhtlvbwlji.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2dmJ5enRibmluaHRsdmJ3bGppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NDQ1NzMsImV4cCI6MjA2NzIyMDU3M30.o1Yj4o2d8u0O58tHVfLhgMyzSFQnl5ZlVmu6EH-jAz0';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: localStorage,
  },
});
